// Font Awesome configuration and icon library setup
import { library } from '@fortawesome/fontawesome-svg-core'
import { 
  faHome, 
  faUser, 
  faBriefcase, 
  faHeart, 
  faEnvelope, 
  faPhone, 
  faGraduationCap, 
  faCode, 
  faShield, 
  faTrophy, 
  faBullseye, 
  faLaptopCode, 
  faServer, 
  faCoffee, 
  faGamepad, 
  faPlane, 
  faCamera, 
  faMusic, 
  faMoon, 
  faSun, 
  faExternalLinkAlt, 
  faEye,
  faStar,
  faMapMarkerAlt,
  faCalendarAlt,
  faTools,
  faNetworkWired,
  faUserShield,
  faBug,
  faRocket,
  faDesktop,
  faMobile,
  faDatabase,
  faCloudDownloadAlt,
  faChartLine,
  faLightbulb,
  faBookOpen,
  faCertificate,
  faAward,
  faHandshake,
  faUsers,
  faChalkboardTeacher,
  faCogs,
  faSearch,
  faFireAlt,
  faTerminal,
  faCodeBranch,
  faGlobe,
  faPalette,
  faCubes,
  faAtom,
  faFlask,
  faBrain,
  faRobot,
  faMicrochip,
  faLock,
  faKey,
  faFingerprint,
  faUserSecret,
  faBinoculars,
  faShieldAlt,
  faExclamationTriangle,
  faSyncAlt,
  faSpinner,
  faCheckCircle,
  faTimesCircle,
  faInfoCircle,
  faArrowRight,
  faArrowLeft,
  faArrowUp,
  faArrowDown,
  faDownload,
  faUpload,
  faShare,
  faLink,
  faExternalLinkSquareAlt,
  faWindowMaximize,
  faExpand,
  faCompress
} from '@fortawesome/free-solid-svg-icons'

import { 
  faGithub, 
  faLinkedin, 
  faPython, 
  faJs, 
  faJava, 
  faReact, 
  faNodeJs, 
  faDocker, 
  faGitAlt, 
  faLinux, 
  faWindows, 
  faApple, 
  faAndroid, 
  faGoogle, 
  faMicrosoft, 
  faAmazon, 
  faDigitalOcean, 
  faStackOverflow, 
  faReddit, 
  faTwitter, 
  faInstagram, 
  faFacebook, 
  faYoutube, 
  faSlack, 
  faDiscord, 
  faTelegram, 
  faWhatsapp,
  faUnity,
  faVuejs,
  faAngular,
  faBootstrap,
  faSass,
  faLess,
  faFigma,
  faSketch,
  faInvision,
  faJira,
  faTrello,
  faConfluence,
  faSlackHash,
  faGitlab,
  faBitbucket,
  faSourcetree,
  faNpm,
  faYarn,
  faUbuntu,
  faDebian,
  faCentos,
  faRedhat,
  faSuse,
  faFreebsd,
  faRaspberryPi,
  faAws,
  faStripe,
  faPaypal,
  faBitcoin,
  faEthereum,
  faAppStore,
  faGooglePlay,
  faChrome,
  faFirefox,
  faEdge,
  faSafari,
  faOpera,
  faInternetExplorer
} from '@fortawesome/free-brands-svg-icons'

import { 
  faEnvelope as farEnvelope, 
  faUser as farUser, 
  faHeart as farHeart, 
  faEye as farEye, 
  faComments as farComments, 
  faLightbulb as farLightbulb, 
  faHandshake as farHandshake, 
  faStar as farStar, 
  faBookmark as farBookmark, 
  faCalendar as farCalendar, 
  faClock as farClock, 
  faFile as farFile, 
  faFolder as farFolder, 
  faImage as farImage, 
  faPaperPlane as farPaperPlane, 
  faThumbsUp as farThumbsUp, 
  faThumbsDown as farThumbsDown, 
  faSmile as farSmile, 
  faFrown as farFrown, 
  faMeh as farMeh, 
  faGrin as farGrin, 
  faLaugh as farLaugh, 
  faAngry as farAngry, 
  faSadTear as farSadTear, 
  faSurprise as farSurprise, 
  faKiss as farKiss, 
  faHeart as farHeartRegular, 
  faCheckCircle as farCheckCircle, 
  faTimesCircle as farTimesCircle, 
  faQuestionCircle as farQuestionCircle, 
  faCommentDots as farCommentDots, 
  faBuilding as farBuilding, 
  faNewspaper as farNewspaper, 
  faAddressCard as farAddressCard, 
  faIdCard as farIdCard, 
  faClipboard as farClipboard, 
  faListAlt as farListAlt, 
  faEdit as farEdit, 
  faTrashAlt as farTrashAlt, 
  faCopy as farCopy, 
  faSave as farSave, 
  faWindowRestore as farWindowRestore, 
  faWindowMinimize as farWindowMinimize, 
  faWindowClose as farWindowClose, 
  faSquare as farSquare, 
  faCheckSquare as farCheckSquare, 
  faMinusSquare as farMinusSquare, 
  faPlusSquare as farPlusSquare, 
  faCircle as farCircle, 
  faDotCircle as farDotCircle, 
  faPlayCircle as farPlayCircle, 
  faStopCircle as farStopCircle, 
  faPauseCircle as farPauseCircle, 
  faCaretSquareLeft as farCaretSquareLeft, 
  faCaretSquareRight as farCaretSquareRight, 
  faCaretSquareUp as farCaretSquareUp, 
  faCaretSquareDown as farCaretSquareDown, 
  faArrowAltCircleLeft as farArrowAltCircleLeft, 
  faArrowAltCircleRight as farArrowAltCircleRight, 
  faArrowAltCircleUp as farArrowAltCircleUp, 
  faArrowAltCircleDown as farArrowAltCircleDown, 
  faHandPointer as farHandPointer, 
  faHandPaper as farHandPaper, 
  faHandRock as farHandRock, 
  faHandPeace as farHandPeace, 
  faHandSpock as farHandSpock, 
  faHandScissors as farHandScissors, 
  faHandLizard as farHandLizard, 
  faGem as farGem, 
  faSnowflake as farSnowflake, 
  faKeyboard as farKeyboard, 
  faBell as farBell, 
  faCompass as farCompass, 
  faMoon as farMoon, 
  faSun as farSun
} from '@fortawesome/free-regular-svg-icons'

// Add icons to the library
library.add(
  // Solid icons
  faHome, faUser, faBriefcase, faHeart, faEnvelope, faPhone, faGraduationCap, faCode, faShield, faTrophy, faBullseye, 
  faLaptopCode, faServer, faCoffee, faGamepad, faPlane, faCamera, faMusic, faMoon, faSun, faExternalLinkAlt, faEye, 
  faStar, faMapMarkerAlt, faCalendarAlt, faTools, faNetworkWired, faUserShield, faBug, faRocket, faDesktop, faMobile, 
  faDatabase, faCloudDownloadAlt, faChartLine, faLightbulb, faBookOpen, faCertificate, faAward, faHandshake, faUsers, 
  faChalkboardTeacher, faCogs, faSearch, faFireAlt, faTerminal, faCodeBranch, faGlobe, faPalette, faCubes, faAtom, 
  faFlask, faBrain, faRobot, faMicrochip, faLock, faKey, faFingerprint, faUserSecret, faBinoculars, 
  faShieldAlt, faExclamationTriangle, faSyncAlt, faSpinner, faCheckCircle, faTimesCircle, faInfoCircle, 
  faArrowRight, faArrowLeft, faArrowUp, faArrowDown, faDownload, faUpload, faShare, faLink, faExternalLinkSquareAlt, 
  faWindowMaximize, faExpand, faCompress,
  
  // Brand icons
  faGithub, faLinkedin, faPython, faJs, faJava, faReact, faNodeJs, faDocker, faGitAlt, faLinux, faWindows, faApple, 
  faAndroid, faGoogle, faMicrosoft, faAmazon, faDigitalOcean, faStackOverflow, faReddit, faTwitter, faInstagram, 
  faFacebook, faYoutube, faSlack, faDiscord, faTelegram, faWhatsapp, faUnity, faVuejs, faAngular, 
  faBootstrap, faSass, faLess, faFigma, faSketch, faInvision, faJira, faTrello, 
  faConfluence, faSlackHash, faGitlab, faBitbucket, faSourcetree, faNpm, faYarn, faUbuntu, faDebian, faCentos, 
  faRedhat, faSuse, faFreebsd, faRaspberryPi, faAws, faStripe, faPaypal, faBitcoin, faEthereum, faAppStore, faGooglePlay, faChrome, 
  faFirefox, faEdge, faSafari, faOpera, faInternetExplorer,
  
  // Regular icons
  farEnvelope, farUser, farHeart, farEye, farComments, farLightbulb, farHandshake, farStar, farBookmark, farCalendar, 
  farClock, farFile, farFolder, farImage, farPaperPlane, farThumbsUp, farThumbsDown, farSmile, 
  farFrown, farMeh, farGrin, farLaugh, farAngry, farSadTear, farSurprise, farKiss, farHeartRegular, farCheckCircle, 
  farTimesCircle, farQuestionCircle, farCommentDots, farBuilding, farNewspaper, 
  farAddressCard, farIdCard, farClipboard, farListAlt, farEdit, farTrashAlt, farCopy, farSave, farWindowRestore, 
  farWindowMinimize, farWindowClose, farSquare, farCheckSquare, farMinusSquare, farPlusSquare, farCircle, farDotCircle, 
  farPlayCircle, farStopCircle, farPauseCircle, farCaretSquareLeft, farCaretSquareRight, farCaretSquareUp, 
  farCaretSquareDown, farArrowAltCircleLeft, farArrowAltCircleRight, farArrowAltCircleUp, farArrowAltCircleDown, 
  farHandPointer, farHandPaper, farHandRock, farHandPeace, farHandSpock, farHandScissors, farHandLizard, farGem, 
  farSnowflake, farKeyboard, farBell, farCompass, farMoon, farSun
)

export default library
